language: go
go:
  - "1.14.x"

services:
  - postgresql
  - mysql

go_import_path: github.com/ottotech/godic

before_install:
  # Go get our deps.
  - go get -v ./...

before_script:
  - createuser -U postgres -s -e test
  - psql -c 'create database test_db;' -U root
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_db;'
  - mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'secret';"

script:
  - go test -v .