dist: xenial

sudo: true

language: go
go:
  - "1.16.x"

services:
  - postgresql
  - mysql

go_import_path: github.com/ottotech/godic

before_install:
  # Go get our deps.
  - go get -v ./...

before_script:
  - createuser -U postgres -s -e test
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version
  - mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'secret';"

script:
  - go test -v .